// Demo data seeder for School ERP - only runs once if localStorage is empty

export interface Student {
  id: number;
  admNo: string;
  name: string;
  fatherName: string;
  motherName: string;
  className: string;
  section: string;
  rollNo: string;
  dob: string;
  contact: string;
  route: string;
  schNo: string;
  oldBalance: number;
  status: "Active" | "Inactive";
  admissionDate?: string;
  aadharNo?: string;
  srNo?: string;
  penNo?: string;
  apaarNo?: string;
  prevSchoolName?: string;
  prevSchoolTcNo?: string;
  prevSchoolLeavingDate?: string;
  prevSchoolClass?: string;
}

export interface Staff {
  id: number;
  name: string;
  designation: string;
  department: string;
  employeeId: string;
  contact: string;
  email: string;
  dob: string;
  joiningDate: string;
  salary: number;
  status: "Active" | "Inactive";
}

const DEMO_STUDENTS: Student[] = [
  {
    id: 1,
    admNo: "ADM-2024-001",
    name: "Aarav Sharma",
    fatherName: "Rajesh Sharma",
    motherName: "Sunita Sharma",
    className: "Class 10",
    section: "A",
    rollNo: "01",
    dob: "2009-04-15",
    contact: "9876543201",
    route: "Route 1 - North",
    schNo: "SCH001",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "1234-5678-9011",
    srNo: "SR-001",
    penNo: "PEN001",
    apaarNo: "AP001",
    prevSchoolName: "Sunrise Public School",
    prevSchoolTcNo: "TC-2024-001",
    prevSchoolLeavingDate: "2024-03-31",
    prevSchoolClass: "Class 9",
  },
  {
    id: 2,
    admNo: "ADM-2024-002",
    name: "Priya Patel",
    fatherName: "Suresh Patel",
    motherName: "Kavita Patel",
    className: "Class 9",
    section: "B",
    rollNo: "02",
    dob: "2010-06-22",
    contact: "9812345678",
    route: "Route 2 - South",
    schNo: "SCH002",
    oldBalance: 500,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "2234-5678-9012",
    srNo: "SR-002",
    penNo: "PEN002",
    apaarNo: "AP002",
    prevSchoolName: "Greenfield Academy",
    prevSchoolTcNo: "TC-2024-002",
    prevSchoolLeavingDate: "2024-03-31",
    prevSchoolClass: "Class 8",
  },
  {
    id: 3,
    admNo: "ADM-2024-003",
    name: "Rohit Kumar",
    fatherName: "Mohan Kumar",
    motherName: "Geeta Kumar",
    className: "Class 8",
    section: "A",
    rollNo: "03",
    dob: "2011-12-05",
    contact: "9887654321",
    route: "Route 3 - East",
    schNo: "SCH003",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "3234-5678-9013",
    srNo: "SR-003",
    penNo: "PEN003",
    apaarNo: "AP003",
    prevSchoolName: "Holy Cross School",
    prevSchoolTcNo: "TC-2024-003",
    prevSchoolLeavingDate: "2024-03-31",
    prevSchoolClass: "Class 7",
  },
  {
    id: 4,
    admNo: "ADM-2024-004",
    name: "Ananya Singh",
    fatherName: "Vikram Singh",
    motherName: "Pooja Singh",
    className: "Class 7",
    section: "A",
    rollNo: "04",
    dob: "2012-03-18",
    contact: "9898765432",
    route: "Route 1 - North",
    schNo: "SCH004",
    oldBalance: 200,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "4234-5678-9014",
    srNo: "SR-004",
    penNo: "PEN004",
    apaarNo: "AP004",
  },
  {
    id: 5,
    admNo: "ADM-2024-005",
    name: "Kavya Nair",
    fatherName: "Krishnan Nair",
    motherName: "Lakshmi Nair",
    className: "Class 6",
    section: "B",
    rollNo: "05",
    dob: "2013-08-30",
    contact: "9876512345",
    route: "Route 2 - South",
    schNo: "SCH005",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "5234-5678-9015",
    srNo: "SR-005",
  },
  {
    id: 6,
    admNo: "ADM-2024-006",
    name: "Arjun Verma",
    fatherName: "Sanjay Verma",
    motherName: "Rekha Verma",
    className: "Class 5",
    section: "A",
    rollNo: "06",
    dob: "2014-11-12",
    contact: "9856789012",
    route: "Route 3 - East",
    schNo: "SCH006",
    oldBalance: 750,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "6234-5678-9016",
    srNo: "SR-006",
  },
  {
    id: 7,
    admNo: "ADM-2024-007",
    name: "Shreya Agarwal",
    fatherName: "Vinay Agarwal",
    motherName: "Meena Agarwal",
    className: "Class 4",
    section: "B",
    rollNo: "07",
    dob: "2015-01-25",
    contact: "9834567890",
    route: "Route 1 - North",
    schNo: "SCH007",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "7234-5678-9017",
    srNo: "SR-007",
  },
  {
    id: 8,
    admNo: "ADM-2024-008",
    name: "Dev Mishra",
    fatherName: "Arun Mishra",
    motherName: "Poonam Mishra",
    className: "Class 3",
    section: "A",
    rollNo: "08",
    dob: "2016-07-09",
    contact: "9823456789",
    route: "Route 2 - South",
    schNo: "SCH008",
    oldBalance: 300,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "8234-5678-9018",
    srNo: "SR-008",
  },
  {
    id: 9,
    admNo: "ADM-2024-009",
    name: "Isha Joshi",
    fatherName: "Deepak Joshi",
    motherName: "Nita Joshi",
    className: "Class 2",
    section: "A",
    rollNo: "09",
    dob: "2017-09-14",
    contact: "9812378901",
    route: "Route 3 - East",
    schNo: "SCH009",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 10,
    admNo: "ADM-2024-010",
    name: "Ravi Mehta",
    fatherName: "Dilip Mehta",
    motherName: "Sonal Mehta",
    className: "Class 1",
    section: "B",
    rollNo: "10",
    dob: "2018-04-03",
    contact: "9801234567",
    route: "Route 1 - North",
    schNo: "SCH010",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 11,
    admNo: "ADM-2024-011",
    name: "Tanvi Gupta",
    fatherName: "Anil Gupta",
    motherName: "Smita Gupta",
    className: "Class 10",
    section: "B",
    rollNo: "11",
    dob: "2009-02-19",
    contact: "9891234560",
    route: "Route 2 - South",
    schNo: "SCH011",
    oldBalance: 1000,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "1134-5678-9021",
    srNo: "SR-011",
  },
  {
    id: 12,
    admNo: "ADM-2024-012",
    name: "Nikhil Rao",
    fatherName: "Prasad Rao",
    motherName: "Vijaya Rao",
    className: "Class 8",
    section: "B",
    rollNo: "12",
    dob: "2011-05-28",
    contact: "9882345671",
    route: "Route 3 - East",
    schNo: "SCH012",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "1234-5688-9022",
    srNo: "SR-012",
  },
  {
    id: 13,
    admNo: "ADM-2024-013",
    name: "Pooja Tiwari",
    fatherName: "Ramnath Tiwari",
    motherName: "Usha Tiwari",
    className: "Class 6",
    section: "A",
    rollNo: "13",
    dob: "2013-10-07",
    contact: "9873456782",
    route: "Route 1 - North",
    schNo: "SCH013",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 14,
    admNo: "ADM-2024-014",
    name: "Manav Jain",
    fatherName: "Sunil Jain",
    motherName: "Sita Jain",
    className: "Class 7",
    section: "B",
    rollNo: "14",
    dob: "2012-12-31",
    contact: "9864567893",
    route: "Route 2 - South",
    schNo: "SCH014",
    oldBalance: 450,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 15,
    admNo: "ADM-2024-015",
    name: "Sania Khan",
    fatherName: "Imran Khan",
    motherName: "Rubina Khan",
    className: "Class 9",
    section: "A",
    rollNo: "15",
    dob: "2010-08-17",
    contact: "9855678904",
    route: "Route 3 - East",
    schNo: "SCH015",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
    aadharNo: "1234-5678-9025",
    srNo: "SR-015",
  },
  {
    id: 16,
    admNo: "ADM-2024-016",
    name: "Rahul Dubey",
    fatherName: "Ashok Dubey",
    motherName: "Mala Dubey",
    className: "Class 5",
    section: "B",
    rollNo: "16",
    dob: "2014-03-22",
    contact: "9846789015",
    route: "Route 1 - North",
    schNo: "SCH016",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 17,
    admNo: "ADM-2024-017",
    name: "Meera Saxena",
    fatherName: "Vivek Saxena",
    motherName: "Anju Saxena",
    className: "Class 4",
    section: "A",
    rollNo: "17",
    dob: "2015-06-11",
    contact: "9837890126",
    route: "Route 2 - South",
    schNo: "SCH017",
    oldBalance: 600,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 18,
    admNo: "ADM-2024-018",
    name: "Krish Yadav",
    fatherName: "Ramesh Yadav",
    motherName: "Saroj Yadav",
    className: "Class 3",
    section: "B",
    rollNo: "18",
    dob: "2016-01-30",
    contact: "9828901237",
    route: "Route 3 - East",
    schNo: "SCH018",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 19,
    admNo: "ADM-2024-019",
    name: "Nisha Chauhan",
    fatherName: "Rajendra Chauhan",
    motherName: "Savita Chauhan",
    className: "Class 2",
    section: "B",
    rollNo: "19",
    dob: "2017-11-08",
    contact: "9819012348",
    route: "Route 1 - North",
    schNo: "SCH019",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
  {
    id: 20,
    admNo: "ADM-2024-020",
    name: "Aditya Pandey",
    fatherName: "Harish Pandey",
    motherName: "Kamala Pandey",
    className: "Class 1",
    section: "A",
    rollNo: "20",
    dob: "2018-07-21",
    contact: "9800123459",
    route: "Route 2 - South",
    schNo: "SCH020",
    oldBalance: 0,
    status: "Active",
    admissionDate: "2024-04-01",
  },
];

const DEMO_STAFF: Staff[] = [
  {
    id: 1,
    name: "Rekha Singh",
    designation: "Principal",
    department: "Administration",
    employeeId: "EMP-001",
    contact: "9811223344",
    email: "rekha.singh@school.edu.in",
    dob: "1975-05-12",
    joiningDate: "2008-07-01",
    salary: 65000,
    status: "Active",
  },
  {
    id: 2,
    name: "Amit Verma",
    designation: "Senior Teacher",
    department: "Science Dept",
    employeeId: "EMP-002",
    contact: "9922334455",
    email: "amit.verma@school.edu.in",
    dob: "1980-09-22",
    joiningDate: "2012-06-15",
    salary: 42000,
    status: "Active",
  },
  {
    id: 3,
    name: "Geeta Joshi",
    designation: "Teacher",
    department: "Maths Dept",
    employeeId: "EMP-003",
    contact: "9933445566",
    email: "geeta.joshi@school.edu.in",
    dob: "1985-03-10",
    joiningDate: "2015-03-10",
    salary: 38000,
    status: "Active",
  },
  {
    id: 4,
    name: "Raju Yadav",
    designation: "Driver",
    department: "Transport",
    employeeId: "EMP-004",
    contact: "9944556677",
    email: "raju.yadav@school.edu.in",
    dob: "1978-11-30",
    joiningDate: "2018-08-20",
    salary: 18000,
    status: "Active",
  },
  {
    id: 5,
    name: "Sunita Sharma",
    designation: "Librarian",
    department: "Library",
    employeeId: "EMP-005",
    contact: "9955667788",
    email: "sunita.sharma@school.edu.in",
    dob: "1982-07-04",
    joiningDate: "2014-04-01",
    salary: 28000,
    status: "Active",
  },
  {
    id: 6,
    name: "Dinesh Tripathi",
    designation: "Accountant",
    department: "Finance",
    employeeId: "EMP-006",
    contact: "9966778899",
    email: "dinesh.tripathi@school.edu.in",
    dob: "1983-02-14",
    joiningDate: "2016-04-01",
    salary: 35000,
    status: "Active",
  },
  {
    id: 7,
    name: "Priya Mehta",
    designation: "Teacher",
    department: "English Dept",
    employeeId: "EMP-007",
    contact: "9977889900",
    email: "priya.mehta@school.edu.in",
    dob: "1990-06-18",
    joiningDate: "2019-07-01",
    salary: 32000,
    status: "Active",
  },
  {
    id: 8,
    name: "Kamal Srivastava",
    designation: "PT Teacher",
    department: "Sports Dept",
    employeeId: "EMP-008",
    contact: "9988990011",
    email: "kamal.srivastava@school.edu.in",
    dob: "1987-12-25",
    joiningDate: "2017-04-01",
    salary: 29000,
    status: "Active",
  },
  {
    id: 9,
    name: "Anjali Dixit",
    designation: "Teacher",
    department: "Social Science",
    employeeId: "EMP-009",
    contact: "9999001122",
    email: "anjali.dixit@school.edu.in",
    dob: "1992-04-08",
    joiningDate: "2020-07-01",
    salary: 30000,
    status: "Active",
  },
  {
    id: 10,
    name: "Manoj Kumar",
    designation: "Peon",
    department: "Administration",
    employeeId: "EMP-010",
    contact: "9900112233",
    email: "manoj.kumar@school.edu.in",
    dob: "1988-08-15",
    joiningDate: "2013-01-01",
    salary: 15000,
    status: "Active",
  },
];

const DEMO_FEE_MASTERS = [
  {
    id: 1,
    heading: "Tuition Fee",
    group: "General",
    account: "Tuition Fees",
    frequency: "Monthly",
    months: [
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
      "Mar",
    ],
  },
  {
    id: 2,
    heading: "Development Fee",
    group: "General",
    account: "Vikas Shulk",
    frequency: "Annual",
    months: [],
  },
  {
    id: 3,
    heading: "Library Fee",
    group: "General",
    account: "Admission Fees",
    frequency: "Annual",
    months: [],
  },
  {
    id: 4,
    heading: "Sports Fee",
    group: "General",
    account: "Admission Fees",
    frequency: "Annual",
    months: [],
  },
  {
    id: 5,
    heading: "Computer Fee",
    group: "General",
    account: "Computer",
    frequency: "Monthly",
    months: [
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
      "Jan",
      "Feb",
      "Mar",
    ],
  },
];

const DEMO_FEE_PLANS = [
  {
    id: 1,
    className: "Class 1",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1200,
  },
  {
    id: 2,
    className: "Class 1",
    category: "General",
    feesHead: "Development Fee",
    value: 2000,
  },
  {
    id: 3,
    className: "Class 1",
    category: "General",
    feesHead: "Library Fee",
    value: 500,
  },
  {
    id: 4,
    className: "Class 1",
    category: "General",
    feesHead: "Sports Fee",
    value: 800,
  },
  {
    id: 5,
    className: "Class 1",
    category: "General",
    feesHead: "Computer Fee",
    value: 300,
  },
  {
    id: 6,
    className: "Class 2",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1300,
  },
  {
    id: 7,
    className: "Class 2",
    category: "General",
    feesHead: "Development Fee",
    value: 2000,
  },
  {
    id: 8,
    className: "Class 2",
    category: "General",
    feesHead: "Library Fee",
    value: 500,
  },
  {
    id: 9,
    className: "Class 2",
    category: "General",
    feesHead: "Sports Fee",
    value: 800,
  },
  {
    id: 10,
    className: "Class 2",
    category: "General",
    feesHead: "Computer Fee",
    value: 350,
  },
  {
    id: 11,
    className: "Class 3",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1400,
  },
  {
    id: 12,
    className: "Class 3",
    category: "General",
    feesHead: "Development Fee",
    value: 2500,
  },
  {
    id: 13,
    className: "Class 3",
    category: "General",
    feesHead: "Sports Fee",
    value: 1000,
  },
  {
    id: 14,
    className: "Class 4",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1500,
  },
  {
    id: 15,
    className: "Class 4",
    category: "General",
    feesHead: "Development Fee",
    value: 2500,
  },
  {
    id: 16,
    className: "Class 5",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1600,
  },
  {
    id: 17,
    className: "Class 5",
    category: "General",
    feesHead: "Development Fee",
    value: 3000,
  },
  {
    id: 18,
    className: "Class 5",
    category: "General",
    feesHead: "Computer Fee",
    value: 400,
  },
  {
    id: 19,
    className: "Class 6",
    category: "General",
    feesHead: "Tuition Fee",
    value: 1800,
  },
  {
    id: 20,
    className: "Class 6",
    category: "General",
    feesHead: "Development Fee",
    value: 3000,
  },
  {
    id: 21,
    className: "Class 7",
    category: "General",
    feesHead: "Tuition Fee",
    value: 2000,
  },
  {
    id: 22,
    className: "Class 7",
    category: "General",
    feesHead: "Development Fee",
    value: 3500,
  },
  {
    id: 23,
    className: "Class 8",
    category: "General",
    feesHead: "Tuition Fee",
    value: 2200,
  },
  {
    id: 24,
    className: "Class 8",
    category: "General",
    feesHead: "Development Fee",
    value: 3500,
  },
  {
    id: 25,
    className: "Class 9",
    category: "General",
    feesHead: "Tuition Fee",
    value: 2500,
  },
  {
    id: 26,
    className: "Class 9",
    category: "General",
    feesHead: "Development Fee",
    value: 4000,
  },
  {
    id: 27,
    className: "Class 9",
    category: "General",
    feesHead: "Computer Fee",
    value: 500,
  },
  {
    id: 28,
    className: "Class 10",
    category: "General",
    feesHead: "Tuition Fee",
    value: 2800,
  },
  {
    id: 29,
    className: "Class 10",
    category: "General",
    feesHead: "Development Fee",
    value: 4000,
  },
  {
    id: 30,
    className: "Class 10",
    category: "General",
    feesHead: "Computer Fee",
    value: 600,
  },
  {
    id: 31,
    className: "Class 10",
    category: "General",
    feesHead: "Library Fee",
    value: 800,
  },
];

const DEMO_FEE_PAYMENTS = [
  {
    id: "pay001",
    receiptNo: "R26-0001",
    date: "2026-04-05",
    admNo: "ADM-2024-001",
    studentName: "Aarav Sharma",
    className: "Class 10",
    months: ["Apr"],
    feeRows: [
      { id: 1, feeHead: "Tuition Fee", months: { Apr: 2800 }, checked: true },
      {
        id: 2,
        feeHead: "Development Fee",
        months: { Apr: 4000 },
        checked: true,
      },
    ],
    otherCharges: [],
    concessionPct: 0,
    concessionAmt: 0,
    netFees: 6800,
    receiptAmt: 6800,
    balance: 0,
    remarks: "",
  },
  {
    id: "pay002",
    receiptNo: "R26-0002",
    date: "2026-04-06",
    admNo: "ADM-2024-002",
    studentName: "Priya Patel",
    className: "Class 9",
    months: ["Apr"],
    feeRows: [
      { id: 1, feeHead: "Tuition Fee", months: { Apr: 2500 }, checked: true },
    ],
    otherCharges: [],
    concessionPct: 0,
    concessionAmt: 0,
    netFees: 2500,
    receiptAmt: 2000,
    balance: 500,
    remarks: "Partial payment",
  },
  {
    id: "pay003",
    receiptNo: "R26-0003",
    date: "2026-04-07",
    admNo: "ADM-2024-003",
    studentName: "Rohit Kumar",
    className: "Class 8",
    months: ["Apr", "May"],
    feeRows: [
      {
        id: 1,
        feeHead: "Tuition Fee",
        months: { Apr: 2200, May: 2200 },
        checked: true,
      },
      {
        id: 2,
        feeHead: "Development Fee",
        months: { Apr: 3500, May: 3500 },
        checked: true,
      },
    ],
    otherCharges: [],
    concessionPct: 0,
    concessionAmt: 0,
    netFees: 11400,
    receiptAmt: 11400,
    balance: 0,
    remarks: "",
  },
  {
    id: "pay004",
    receiptNo: "R26-0004",
    date: "2026-04-08",
    admNo: "ADM-2024-005",
    studentName: "Kavya Nair",
    className: "Class 6",
    months: ["Apr"],
    feeRows: [
      { id: 1, feeHead: "Tuition Fee", months: { Apr: 1800 }, checked: true },
    ],
    otherCharges: [],
    concessionPct: 0,
    concessionAmt: 0,
    netFees: 1800,
    receiptAmt: 1800,
    balance: 0,
    remarks: "",
  },
  {
    id: "pay005",
    receiptNo: "R26-0005",
    date: "2026-04-10",
    admNo: "ADM-2024-011",
    studentName: "Tanvi Gupta",
    className: "Class 10",
    months: ["Apr"],
    feeRows: [
      { id: 1, feeHead: "Tuition Fee", months: { Apr: 2800 }, checked: true },
    ],
    otherCharges: [],
    concessionPct: 0,
    concessionAmt: 0,
    netFees: 2800,
    receiptAmt: 1800,
    balance: 1000,
    remarks: "Pending 1000",
  },
];

export function seedDemoDataIfEmpty(): void {
  try {
    // Check existing students
    const existingStudents = JSON.parse(
      localStorage.getItem("erp_students") || "[]",
    );
    if (existingStudents.length > 0) return; // Data already present - skip

    // Seed students
    localStorage.setItem("erp_students", JSON.stringify(DEMO_STUDENTS));

    // Seed staff
    const existingStaff = JSON.parse(localStorage.getItem("erp_staff") || "[]");
    if (existingStaff.length === 0) {
      localStorage.setItem("erp_staff", JSON.stringify(DEMO_STAFF));
    }

    // Seed fee masters
    const existingMasters = JSON.parse(
      localStorage.getItem("erp_fee_masters") || "[]",
    );
    if (existingMasters.length === 0) {
      localStorage.setItem("erp_fee_masters", JSON.stringify(DEMO_FEE_MASTERS));
    }

    // Seed fee plans
    const existingPlans = JSON.parse(
      localStorage.getItem("erp_fee_plans") || "[]",
    );
    if (existingPlans.length === 0) {
      localStorage.setItem("erp_fee_plans", JSON.stringify(DEMO_FEE_PLANS));
    }

    // Seed fee payments
    const existingPayments = JSON.parse(
      localStorage.getItem("erp_fee_payments") || "[]",
    );
    if (existingPayments.length === 0) {
      localStorage.setItem(
        "erp_fee_payments",
        JSON.stringify(DEMO_FEE_PAYMENTS),
      );
    }
  } catch (e) {
    console.warn("Demo data seeding failed:", e);
  }
}
